//! Plan state — the data structure behind plan-mode execution and the
//! sequential-gate validation that prevents the model from skipping ahead.
//!
//! Lifecycle:
//!   1. `EnterPlanMode` flips a session-level mode (handled elsewhere)
//!   2. Model explores using read-only tools, then calls `SubmitPlan`
//!      → `submit()` here, replacing any previous draft
//!   3. User approves; model executes step by step, calling
//!      `UpdatePlanStep` per transition → `update_step()` here applies
//!      Layer-1 transition gating
//!   4. `ExitPlanMode` flips mode back; the plan can stay around as a
//!      visible record (sidebar UI subscribes), or `clear()` drops it
//!
//! Layer-1 gating means: the model can't claim step N is in_progress
//! while step N-1 is still todo / in_progress / failed. The tool returns
//! a structured error string that the model reads on the next turn and
//! self-corrects (same honor-system as Anthropic's tool errors). Combined
//! with system-reminder injection (Layer 2, separate change) we get a
//! Ralph-style "one step at a time" execution loop.
//!
//! Storage: a single in-process `Mutex<Option<Plan>>` keyed off a
//! `OnceLock`. Sessions don't share plans yet — that's plumbed in a
//! follow-up via `WorkerState::current_plan` once the IPC and persistence
//! shape settles.

use serde::{Deserialize, Serialize};
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Mutex, OnceLock};

/// Step states ordered by lifecycle. `Failed` is terminal-but-retryable
/// (a step can be re-entered as `InProgress` if the user wants to retry).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StepStatus {
    Todo,
    InProgress,
    Done,
    Failed,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanStep {
    pub id: String,
    pub title: String,
    pub description: String,
    pub status: StepStatus,
    /// Free-form note set by `UpdatePlanStep` — typically the failure
    /// reason when status is `Failed`, or progress detail. Not required
    /// for happy-path transitions.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    /// Cross-step data channel (M6.3). Set by `UpdatePlanStep(done)`
    /// when the step produced data later steps need to consume — a
    /// generated id, a hash, a path, a port number. Surfaced in the
    /// next step's continuation prompt so the model can read prior
    /// outputs without relying on the chat history (which gets
    /// compacted between steps in M6.2). Capped at ~1KB at the tool
    /// boundary to keep the prompt lean.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    /// Stable plan id, generated by `submit`. Useful when the sidebar
    /// wants to distinguish "the model replaced the plan" (new id) from
    /// "the model amended a step" (same id, different step states).
    pub id: String,
    pub steps: Vec<PlanStep>,
}

impl Plan {
    /// Index of the step currently `InProgress`, if any. Plans are
    /// strictly sequential under Layer-1 gating, so at most one step
    /// can be `InProgress` at a time.
    pub fn current_step_idx(&self) -> Option<usize> {
        self.steps
            .iter()
            .position(|s| s.status == StepStatus::InProgress)
    }

    pub fn step_by_id(&self, id: &str) -> Option<&PlanStep> {
        self.steps.iter().find(|s| s.id == id)
    }

    fn step_by_id_mut(&mut self, id: &str) -> Option<&mut PlanStep> {
        self.steps.iter_mut().find(|s| s.id == id)
    }

    fn position(&self, id: &str) -> Option<usize> {
        self.steps.iter().position(|s| s.id == id)
    }
}

/// Process-wide single-plan slot. There's exactly one active session
/// per GUI process (Terminal + Chat tabs share `SharedSession`); a
/// `/load` swap restores the loaded session's plan into this slot.
fn slot() -> &'static Mutex<Option<Plan>> {
    static SLOT: OnceLock<Mutex<Option<Plan>>> = OnceLock::new();
    SLOT.get_or_init(|| Mutex::new(None))
}

/// Broadcaster registered by [`crate::shared_session`] at worker boot.
/// Called after every state mutation (submit / update_step / clear)
/// with the new plan snapshot — `None` means cleared. The GUI layer
/// turns this into a `ViewEvent::PlanUpdate` so the sidebar updates
/// live; the CLI layer ignores it (terminal renders plan as text via
/// a different path in M5).
type Broadcaster = Box<dyn Fn(Option<Plan>) + Send + Sync>;

fn broadcaster() -> &'static Mutex<Option<Broadcaster>> {
    static B: OnceLock<Mutex<Option<Broadcaster>>> = OnceLock::new();
    B.get_or_init(|| Mutex::new(None))
}

/// Register a broadcaster to be invoked after every plan mutation.
/// Replaces any prior registration — there's only one active GUI
/// session worker at a time. Pass a closure that captures the
/// `events_tx` you want plan deltas to land on.
pub fn set_broadcaster<F>(f: F)
where
    F: Fn(Option<Plan>) + Send + Sync + 'static,
{
    if let Ok(mut g) = broadcaster().lock() {
        *g = Some(Box::new(f));
    }
}

fn fire(plan: Option<Plan>) {
    if let Ok(g) = broadcaster().lock() {
        if let Some(f) = g.as_ref() {
            f(plan);
        }
    }
}

/// Stalled-turn detector counter (M4.4). Tracks "consecutive agent
/// turns that ended without progressing the plan" — every plan
/// mutation (`submit` / `update_step` / `force_step_done`) resets it
/// to zero, every agent turn that ends without one increments it.
/// The shared-session worker reads this after each turn and emits a
/// `ViewEvent::PlanStalled` broadcast when the counter crosses
/// `STALL_TURN_THRESHOLD`. Helps the user notice when the model is
/// looping without making progress on a long-running plan.
fn stall_counter() -> &'static AtomicUsize {
    static SLOT: OnceLock<AtomicUsize> = OnceLock::new();
    SLOT.get_or_init(|| AtomicUsize::new(0))
}

/// Threshold for the stalled-turn detector. After N consecutive turns
/// with no plan progress, the worker fires `ViewEvent::PlanStalled`.
/// Three is a balance: long single-turn jobs (a slow Bash command, a
/// heavy refactor) don't trigger it, but a model genuinely stuck in a
/// reading-and-thinking loop without committing does.
pub const STALL_TURN_THRESHOLD: usize = 3;

/// M6.1 Ralph-loop per-step retry budget. After this many consecutive
/// driver-triggered turns on the same step without it transitioning to
/// Done or Failed, the driver force-marks the step Failed. Bounds
/// runaway loops on individual steps without starving the rest of the
/// plan — a single bad step can't burn through the global iteration cap.
pub const MAX_RETRIES_PER_STEP: usize = 3;

fn reset_stall_counter() {
    stall_counter().store(0, Ordering::Relaxed);
}

/// Per-step attempt tracker (M6.1). Records the step id the driver is
/// currently iterating on, plus the number of times the driver has
/// woken the agent loop for that step without the step transitioning
/// to Done or Failed. Enables the per-step retry budget without having
/// to scan the whole plan history.
fn step_attempts() -> &'static Mutex<Option<(String, usize)>> {
    static SLOT: OnceLock<Mutex<Option<(String, usize)>>> = OnceLock::new();
    SLOT.get_or_init(|| Mutex::new(None))
}

/// Note that the driver is about to nudge the agent for `step_id`.
/// If this is the first nudge for this step, returns 1. Subsequent
/// nudges for the same step return 2, 3, … The counter resets when
/// the driver moves on to a different step.
pub fn note_step_attempt(step_id: &str) -> usize {
    if let Ok(mut g) = step_attempts().lock() {
        let next = match g.as_ref() {
            Some((prev, n)) if prev == step_id => n + 1,
            _ => 1,
        };
        *g = Some((step_id.to_string(), next));
        next
    } else {
        // Lock poisoned — be conservative and return a high number so
        // the driver bails rather than spinning.
        usize::MAX
    }
}

fn reset_step_attempts() {
    if let Ok(mut g) = step_attempts().lock() {
        *g = None;
    }
}

/// External reset used when the user hits Retry / Skip / Continue on
/// the sidebar — gives the model a fresh budget for the same step.
pub fn reset_step_attempts_external() {
    reset_step_attempts();
}

/// Called by the worker after each agent turn that ended without a
/// plan mutation. Returns the new counter value so the caller can
/// decide whether to broadcast PlanStalled. The worker is responsible
/// for the "is the plan even active?" check before calling this.
pub fn note_turn_completed_without_progress() -> usize {
    stall_counter().fetch_add(1, Ordering::Relaxed) + 1
}

/// Snapshot of the current stall count. Used by the "Continue" sidebar
/// button's IPC handler to reset state without making the model run.
pub fn reset_stall_counter_external() {
    reset_stall_counter();
}

/// Replace the slot's contents wholesale (for `/load` restore). Fires
/// the broadcaster so the sidebar redraws on session swap. Pass `None`
/// to clear without explicit broadcast (use `clear()` instead in that
/// case — kept private to discourage misuse).
pub fn restore_from_session(plan: Option<Plan>) {
    if let Ok(mut g) = slot().lock() {
        *g = plan.clone();
    }
    fire(plan);
}

/// Read-only snapshot. Returns `None` when no plan is active.
pub fn get() -> Option<Plan> {
    slot().lock().ok().and_then(|g| g.clone())
}

/// Replace the active plan with a freshly-submitted one. Any prior
/// plan is discarded — re-submission is the model's "I changed my mind"
/// channel. Returns the persisted plan so callers can echo the assigned
/// id back to the model.
pub fn submit(steps: Vec<PlanStep>) -> Result<Plan, String> {
    if steps.is_empty() {
        return Err("plan must have at least one step".into());
    }
    let mut seen = std::collections::HashSet::new();
    for s in &steps {
        if s.id.trim().is_empty() {
            return Err("step id cannot be empty".into());
        }
        if !seen.insert(&s.id) {
            return Err(format!("duplicate step id: {}", s.id));
        }
        if s.title.trim().is_empty() {
            return Err(format!("step {} has empty title", s.id));
        }
    }
    let plan = Plan {
        id: format!("plan-{}", uuid::Uuid::new_v4()),
        steps: steps
            .into_iter()
            .map(|mut s| {
                // Ignore submitted status — every step starts Todo.
                // Lets the schema accept just {id, title, description}
                // without forcing the model to spell out a redundant
                // `"status": "todo"` on every entry.
                s.status = StepStatus::Todo;
                s.note = None;
                s
            })
            .collect(),
    };
    *slot().lock().map_err(|_| "plan slot poisoned")? = Some(plan.clone());
    reset_stall_counter();
    reset_step_attempts();
    fire(Some(plan.clone()));
    Ok(plan)
}

/// Apply a step transition with Layer-1 gating. Returns the updated
/// plan on success, or a human-readable error string the tool surface
/// can echo back to the model as a `tool_result`.
///
/// Legal transitions:
///   Todo → InProgress       — only when the previous step is Done
///   Todo → Failed           — "blocked by upstream failure" path
///                              (M6.7). Note REQUIRED so the audit trail
///                              records why a step that was never
///                              attempted got marked Failed. Used when
///                              an earlier step's failure makes this
///                              step infeasible (e.g. step 2 failed to
///                              scaffold the project, so step 3 has no
///                              files to edit).
///   InProgress → Done       — finishing the current step
///   InProgress → Failed     — current step blew up (note recommended)
///   Failed → InProgress     — retry a failed step
///   Done → InProgress       — REJECTED (re-opening done work would
///                              break the gate's invariants; the model
///                              should submit a new plan instead)
pub fn update_step(
    step_id: &str,
    new_status: StepStatus,
    note: Option<String>,
) -> Result<Plan, String> {
    let mut guard = slot().lock().map_err(|_| "plan slot poisoned")?;
    let plan = guard
        .as_mut()
        .ok_or_else(|| "no active plan — call SubmitPlan first".to_string())?;

    let idx = plan
        .position(step_id)
        .ok_or_else(|| format!("unknown step id: {step_id}"))?;
    let current_status = plan.steps[idx].status;

    match (current_status, new_status) {
        (StepStatus::Todo, StepStatus::InProgress) => {
            if idx > 0 && plan.steps[idx - 1].status != StepStatus::Done {
                return Err(format!(
                    "cannot start step {idx} (\"{}\") — step {} (\"{}\") is currently {:?}, not Done. \
                     Finish or fail the previous step first.",
                    plan.steps[idx].title,
                    idx - 1,
                    plan.steps[idx - 1].title,
                    plan.steps[idx - 1].status,
                ));
            }
        }
        // M6.7: Todo → Failed is the "blocked by upstream failure"
        // path. Allowed without a prior-step-Done check (the whole
        // point is that the prior step DIDN'T finish), but the note
        // is REQUIRED so the audit trail records *why* a step that
        // was never attempted got marked Failed.
        (StepStatus::Todo, StepStatus::Failed) => {
            let note_blank = note.as_deref().map(|s| s.trim().is_empty()).unwrap_or(true);
            if note_blank {
                return Err(format!(
                    "marking step {idx} (\"{}\") Todo → Failed requires a note explaining why \
                     the step is blocked (e.g. \"step 2 failed; no project files to edit\"). \
                     Pass `note: \"<one-line reason>\"` on the UpdatePlanStep call.",
                    plan.steps[idx].title,
                ));
            }
        }
        (StepStatus::InProgress, StepStatus::Done | StepStatus::Failed) => {}
        (StepStatus::Failed, StepStatus::InProgress) => {}
        (from, to) => {
            return Err(format!(
                "illegal step transition {from:?} → {to:?} on step {step_id} (\"{}\")",
                plan.steps[idx].title
            ));
        }
    }

    let step = plan.step_by_id_mut(step_id).expect("just resolved above");
    step.status = new_status;
    if note.is_some() {
        step.note = note;
    }
    let snapshot = plan.clone();
    drop(guard);
    reset_stall_counter();
    // NOTE (M6.13 C3 review): we deliberately do NOT reset
    // step_attempts here. update_step is the per-transition mutation
    // path; resetting would let the model wipe its own retry budget
    // by repeatedly calling UpdatePlanStep without progressing. The
    // budget-driven force-fail in shared_session::drive_turn_stream
    // depends on note_step_attempt incrementing across same-id calls.
    // force_step_done DOES reset (see below) — that's safe because
    // the next actionable step always has a different id.
    fire(Some(snapshot.clone()));

    // Plan-completion auto-restore (M3). When the final step transitions
    // to Done, the plan's job is finished — restore whatever permission
    // mode the user was in before EnterPlanMode flipped them into Plan,
    // so they don't stay parked in `Auto` (which Approve set) for
    // subsequent unrelated work. Cheap to check; the cross-module call
    // into `permissions` is fine because plan_state is a leaf module.
    //
    // We DON'T clear the plan slot here — the sidebar's "All complete"
    // celebration footer relies on the all-done plan staying visible.
    // The (Plan, Some(p)) reminder branch and the sidebar's Approve
    // button visibility check both detect all-done separately and
    // do the right thing (M6.9 — see build_plan_reminder + PlanSidebar
    // showApprove).
    let all_done = snapshot.steps.iter().all(|s| s.status == StepStatus::Done);
    if all_done {
        if let Some(restored) = crate::permissions::take_pre_plan_mode() {
            crate::permissions::set_current_mode_and_broadcast(restored);
        }
    }
    Ok(snapshot)
}

/// User-driven force-Done (M4.2). Skips a step without going through
/// the normal `update_step` gate — used by the sidebar Skip button on
/// failed steps. Records `note` (typically "skipped by user") on the
/// step so the model sees the override on its next turn and audit
/// trails capture the user-initiated transition.
///
/// Unlike `update_step`, this DOES allow Failed → Done. That violates
/// the gate's invariant that "every Done step was actually completed",
/// which is the price of giving the user a Skip button. The note field
/// is the audit record. Triggers the same plan-completion auto-restore
/// as `update_step` if this skip flips the plan to all-done.
pub fn force_step_done(step_id: &str, note: &str) -> Result<Plan, String> {
    let mut guard = slot().lock().map_err(|_| "plan slot poisoned")?;
    let plan = guard.as_mut().ok_or_else(|| "no active plan".to_string())?;

    let step = plan
        .step_by_id_mut(step_id)
        .ok_or_else(|| format!("unknown step id: {step_id}"))?;
    step.status = StepStatus::Done;
    step.note = Some(note.to_string());

    let snapshot = plan.clone();
    drop(guard);
    reset_stall_counter();
    // M6.13 (C3): symmetry with update_step's transition. force-Done
    // is a status mutation just like update_step's transitions and
    // should clear the per-step attempt counter for the same reason.
    reset_step_attempts();
    fire(Some(snapshot.clone()));

    let all_done = snapshot.steps.iter().all(|s| s.status == StepStatus::Done);
    if all_done {
        if let Some(restored) = crate::permissions::take_pre_plan_mode() {
            crate::permissions::set_current_mode_and_broadcast(restored);
        }
    }
    Ok(snapshot)
}

/// Maximum byte length of a step's `output` field. Caps the cross-step
/// data channel at a sane size so a runaway model can't push 100KB of
/// "output" into the next step's prompt and blow context budget. Real
/// step outputs (UUIDs, hashes, paths, port numbers, file lists) fit
/// comfortably in 1KB.
pub const MAX_STEP_OUTPUT_LEN: usize = 1024;

/// UTF-8 safe truncation. `s.len()` is byte length and `s[..N]` panics
/// when N falls inside a multi-byte character (Thai / Chinese / Arabic
/// / emoji). M6.9 fix for the panic that surfaced when a Thai-language
/// step output crossed the 1024-byte cap mid-character. We walk to the
/// largest char boundary ≤ `max_bytes` instead and append the
/// truncation marker only when we actually trimmed.
fn truncate_at_char_boundary(s: String, max_bytes: usize) -> String {
    if s.len() <= max_bytes {
        return s;
    }
    // Find the last char boundary at or below max_bytes. `floor_char_boundary`
    // is unstable in the standard library, so do it manually.
    let mut cut = max_bytes;
    while cut > 0 && !s.is_char_boundary(cut) {
        cut -= 1;
    }
    let mut truncated = String::with_capacity(cut + 16);
    truncated.push_str(&s[..cut]);
    truncated.push_str(" … [truncated]");
    truncated
}

/// Set or clear a step's `output` field (M6.3 cross-step data channel).
/// Truncated to `MAX_STEP_OUTPUT_LEN` bytes with a `… [truncated]`
/// suffix when the model overshoots.
///
/// Decoupled from `update_step` so call sites that only need to set
/// status (sidebar Retry, driver force-Failed) don't have to thread
/// an `output` argument through. The `UpdatePlanStep` tool calls both
/// `update_step` and then `set_step_output` when the model populates
/// the field.
pub fn set_step_output(step_id: &str, output: Option<String>) -> Result<Plan, String> {
    let mut guard = slot().lock().map_err(|_| "plan slot poisoned")?;
    let plan = guard.as_mut().ok_or_else(|| "no active plan".to_string())?;

    let step = plan
        .step_by_id_mut(step_id)
        .ok_or_else(|| format!("unknown step id: {step_id}"))?;

    step.output = output.map(|s| truncate_at_char_boundary(s, MAX_STEP_OUTPUT_LEN));

    let snapshot = plan.clone();
    drop(guard);
    fire(Some(snapshot.clone()));
    Ok(snapshot)
}

/// Drop the active plan. Called by `ExitPlanMode` when the user cancels
/// or after the final step is `Done` and the user dismisses the sidebar.
pub fn clear() {
    if let Ok(mut g) = slot().lock() {
        *g = None;
    }
    reset_step_attempts();
    fire(None);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// All plan_state tests touch the same process-global plan slot,
    /// stall counter, and step-attempt counter — so they must run
    /// serially to avoid `clear()` / `submit()` calls in one test
    /// interleaving with another and producing false "no active plan"
    /// or "unknown step id" failures. This RAII guard is acquired at
    /// the top of every test; it's released when the guard drops.
    fn test_lock() -> std::sync::MutexGuard<'static, ()> {
        static M: std::sync::Mutex<()> = std::sync::Mutex::new(());
        match M.lock() {
            Ok(g) => g,
            // Poison from a panic in another test is harmless for our
            // purposes — recover and proceed so a single failing test
            // doesn't cascade into all subsequent tests.
            Err(p) => p.into_inner(),
        }
    }

    fn step(id: &str, title: &str) -> PlanStep {
        PlanStep {
            id: id.into(),
            title: title.into(),
            description: String::new(),
            status: StepStatus::Todo,
            note: None,
            output: None,
        }
    }

    fn fresh_submit(n: usize) -> Plan {
        clear();
        submit(
            (0..n)
                .map(|i| step(&format!("s{i}"), &format!("Step {i}")))
                .collect(),
        )
        .unwrap()
    }

    #[test]
    fn submit_assigns_id_and_resets_statuses_to_todo() {
        let _g = test_lock();
        clear();
        let plan = submit(vec![PlanStep {
            id: "a".into(),
            title: "first".into(),
            description: "desc".into(),
            status: StepStatus::InProgress, // model tried to lie — should be reset
            note: Some("from the model".into()),
            output: None,
        }])
        .unwrap();
        assert!(plan.id.starts_with("plan-"));
        assert_eq!(plan.steps[0].status, StepStatus::Todo);
        assert_eq!(plan.steps[0].note, None);
    }

    #[test]
    fn submit_rejects_empty_plan() {
        let _g = test_lock();
        clear();
        assert!(submit(vec![]).is_err());
    }

    #[test]
    fn submit_rejects_duplicate_step_ids() {
        let _g = test_lock();
        clear();
        let err = submit(vec![step("a", "x"), step("a", "y")]).unwrap_err();
        assert!(err.contains("duplicate"));
    }

    #[test]
    fn submit_rejects_blank_id_or_title() {
        let _g = test_lock();
        clear();
        assert!(submit(vec![step("", "x")]).is_err());
        assert!(submit(vec![step("a", "  ")]).is_err());
    }

    #[test]
    fn legal_happy_path_done_steps_advance_one_at_a_time() {
        let _g = test_lock();
        fresh_submit(3);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();
        update_step("s1", StepStatus::InProgress, None).unwrap();
        let plan = update_step("s1", StepStatus::Done, None).unwrap();
        assert_eq!(plan.steps[0].status, StepStatus::Done);
        assert_eq!(plan.steps[1].status, StepStatus::Done);
        assert_eq!(plan.steps[2].status, StepStatus::Todo);
    }

    #[test]
    fn skipping_ahead_is_rejected() {
        let _g = test_lock();
        fresh_submit(3);
        // Try to start step 2 without finishing step 0 + 1.
        let err = update_step("s2", StepStatus::InProgress, None).unwrap_err();
        assert!(err.contains("step 1"), "got: {err}");
        // Finish step 0 only.
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();
        // Still can't jump to step 2.
        let err = update_step("s2", StepStatus::InProgress, None).unwrap_err();
        assert!(err.contains("step 1"), "got: {err}");
    }

    #[test]
    fn marking_done_without_in_progress_is_rejected() {
        let _g = test_lock();
        fresh_submit(2);
        let err = update_step("s0", StepStatus::Done, None).unwrap_err();
        assert!(err.contains("illegal"), "got: {err}");
    }

    #[test]
    fn todo_to_failed_with_note_is_legal() {
        // M6.7: "blocked by upstream failure" — a downstream Todo
        // step can transition to Failed without ever going through
        // InProgress, as long as a note explains why. This unblocks
        // the gate from rejecting the model's "step 3 can't run
        // because step 2 failed" recovery.
        let _g = test_lock();
        fresh_submit(3);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Failed, Some("upstream broke".into())).unwrap();
        // s1 is still Todo; mark it Failed as blocked-by-upstream.
        let plan = update_step(
            "s1",
            StepStatus::Failed,
            Some("blocked by step 1 failure".into()),
        )
        .unwrap();
        assert_eq!(plan.steps[1].status, StepStatus::Failed);
        assert_eq!(
            plan.steps[1].note.as_deref(),
            Some("blocked by step 1 failure"),
        );
    }

    #[test]
    fn todo_to_failed_without_note_is_rejected() {
        // The audit trail is only useful when every Failed step has
        // a reason. A Todo step that was never attempted has no
        // implicit context, so the note is REQUIRED — without it the
        // sidebar just shows ✕ on a vague label.
        let _g = test_lock();
        fresh_submit(2);
        let err = update_step("s0", StepStatus::Failed, None).unwrap_err();
        assert!(err.contains("requires a note"), "got: {err}");

        // Whitespace-only note also rejected.
        let err = update_step("s0", StepStatus::Failed, Some("   ".into())).unwrap_err();
        assert!(err.contains("requires a note"), "got: {err}");

        // With a real note it goes through.
        let plan = update_step("s0", StepStatus::Failed, Some("can't access API".into())).unwrap();
        assert_eq!(plan.steps[0].status, StepStatus::Failed);
    }

    #[test]
    fn failed_step_can_be_retried() {
        let _g = test_lock();
        fresh_submit(2);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        let plan = update_step("s0", StepStatus::Failed, Some("ENV var missing".into())).unwrap();
        assert_eq!(plan.steps[0].status, StepStatus::Failed);
        assert_eq!(plan.steps[0].note.as_deref(), Some("ENV var missing"));

        // Retry: failed → in_progress is legal.
        let plan = update_step("s0", StepStatus::InProgress, None).unwrap();
        assert_eq!(plan.steps[0].status, StepStatus::InProgress);
    }

    #[test]
    fn done_step_cannot_be_re_opened() {
        let _g = test_lock();
        fresh_submit(2);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();
        // Re-opening a done step would let the model rewrite history.
        // Force them to submit a new plan instead.
        let err = update_step("s0", StepStatus::InProgress, None).unwrap_err();
        assert!(err.contains("illegal"), "got: {err}");
    }

    #[test]
    fn current_step_idx_tracks_in_progress() {
        let _g = test_lock();
        fresh_submit(3);
        assert_eq!(get().unwrap().current_step_idx(), None);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        assert_eq!(get().unwrap().current_step_idx(), Some(0));
        update_step("s0", StepStatus::Done, None).unwrap();
        assert_eq!(get().unwrap().current_step_idx(), None);
        update_step("s1", StepStatus::InProgress, None).unwrap();
        assert_eq!(get().unwrap().current_step_idx(), Some(1));
    }

    #[test]
    fn update_without_active_plan_errors() {
        let _g = test_lock();
        clear();
        let err = update_step("s0", StepStatus::InProgress, None).unwrap_err();
        assert!(err.contains("no active plan"), "got: {err}");
    }

    #[test]
    fn unknown_step_id_errors() {
        let _g = test_lock();
        fresh_submit(2);
        let err = update_step("nonexistent", StepStatus::InProgress, None).unwrap_err();
        assert!(err.contains("unknown step id"), "got: {err}");
    }

    #[test]
    fn force_step_done_bypasses_gate_and_records_note() {
        // User-driven Skip (M4.2) — force-Done from any state including
        // Failed, with the note captured for audit. Normally Failed →
        // Done would be rejected by the gate.
        let _g = test_lock();
        fresh_submit(3);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Failed, Some("transient".into())).unwrap();

        // Gate would reject Failed → Done via the normal path:
        let err = update_step("s0", StepStatus::Done, None).unwrap_err();
        assert!(
            err.contains("illegal"),
            "gate must reject Failed→Done normally"
        );

        // Force-Done bypasses the gate.
        let plan = force_step_done("s0", "skipped by user").unwrap();
        assert_eq!(plan.steps[0].status, StepStatus::Done);
        assert_eq!(plan.steps[0].note.as_deref(), Some("skipped by user"));

        // Subsequent step can now start (gate's "previous step done"
        // check passes regardless of how the previous step got to Done).
        update_step("s1", StepStatus::InProgress, None).unwrap();
    }

    #[test]
    fn force_step_done_unknown_id_errors() {
        let _g = test_lock();
        fresh_submit(2);
        let err = force_step_done("nope", "skipped by user").unwrap_err();
        assert!(err.contains("unknown step id"));
    }

    #[test]
    fn note_step_attempt_counts_consecutive_attempts() {
        let _g = test_lock();
        reset_step_attempts();
        assert_eq!(note_step_attempt("s0"), 1);
        assert_eq!(note_step_attempt("s0"), 2);
        assert_eq!(note_step_attempt("s0"), 3);
    }

    #[test]
    fn note_step_attempt_resets_on_step_change() {
        let _g = test_lock();
        reset_step_attempts();
        assert_eq!(note_step_attempt("s0"), 1);
        assert_eq!(note_step_attempt("s0"), 2);
        // Driver moves on to s1 — counter should reset to 1.
        assert_eq!(note_step_attempt("s1"), 1);
        // Going back to s0 also resets (new run on the same id).
        assert_eq!(note_step_attempt("s0"), 1);
    }

    #[test]
    fn submit_resets_step_attempts() {
        // Build up some attempts, then submit a new plan — the
        // attempt counter must not leak across plans (otherwise the
        // first step of the new plan would be artificially close to
        // the retry budget cap).
        let _g = test_lock();
        reset_step_attempts();
        note_step_attempt("s0");
        note_step_attempt("s0");
        let _ = submit(vec![step("s0", "first")]).unwrap();
        // Same id, but counter should have reset on submit.
        assert_eq!(note_step_attempt("s0"), 1);
    }

    #[test]
    fn clear_resets_step_attempts() {
        let _g = test_lock();
        reset_step_attempts();
        note_step_attempt("s0");
        note_step_attempt("s0");
        clear();
        assert_eq!(note_step_attempt("s0"), 1);
    }

    #[test]
    fn set_step_output_persists_value() {
        let _g = test_lock();
        fresh_submit(2);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();

        let plan = set_step_output("s0", Some("user-id: abc-123".into())).unwrap();
        assert_eq!(plan.steps[0].output.as_deref(), Some("user-id: abc-123"));
    }

    #[test]
    fn set_step_output_truncates_oversize_values() {
        let _g = test_lock();
        fresh_submit(1);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();

        // Oversize input — model dumped a whole file's contents into output.
        let huge = "x".repeat(MAX_STEP_OUTPUT_LEN + 500);
        let plan = set_step_output("s0", Some(huge)).unwrap();
        let out = plan.steps[0].output.as_ref().unwrap();
        assert!(out.len() < MAX_STEP_OUTPUT_LEN + 100, "must be truncated");
        assert!(
            out.ends_with("[truncated]"),
            "missing truncation marker: {out}"
        );
    }

    #[test]
    fn set_step_output_handles_multibyte_utf8_at_truncation_boundary() {
        // M6.9 (Bug A1): a Thai-language step output > MAX_STEP_OUTPUT_LEN
        // bytes used to panic with "byte index N is not a char boundary"
        // because we sliced `s[..MAX_STEP_OUTPUT_LEN]` directly. The fix
        // walks back to the largest char boundary ≤ the cap.
        //
        // This test deliberately constructs a string whose byte at
        // index MAX_STEP_OUTPUT_LEN falls *inside* a multi-byte char,
        // so the old code would panic on it.
        let _g = test_lock();
        fresh_submit(1);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();

        let mut huge = String::new();
        // Thai script: each character is 3 bytes in UTF-8.
        while huge.len() <= MAX_STEP_OUTPUT_LEN {
            huge.push_str("เก็บข้อมูล");
        }
        // Sanity: the cut point must NOT be a char boundary, otherwise
        // this test wouldn't actually exercise the fix.
        assert!(
            !huge.is_char_boundary(MAX_STEP_OUTPUT_LEN),
            "test setup must produce a non-boundary cut to exercise the bug",
        );

        // Old code would panic here. Fix walks back to a char boundary.
        let plan = set_step_output("s0", Some(huge)).unwrap();
        let out = plan.steps[0].output.as_ref().unwrap();
        assert!(out.ends_with("[truncated]"));
        // No replacement chars (U+FFFD) → truncation landed cleanly.
        assert!(
            !out.contains('\u{FFFD}'),
            "truncation produced invalid UTF-8: {out}",
        );
    }

    #[test]
    fn set_step_output_clear_with_none() {
        let _g = test_lock();
        fresh_submit(1);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();
        set_step_output("s0", Some("first".into())).unwrap();

        let plan = set_step_output("s0", None).unwrap();
        assert_eq!(plan.steps[0].output, None, "None must clear the field");
    }

    #[test]
    fn set_step_output_unknown_id_errors() {
        let _g = test_lock();
        fresh_submit(2);
        let err = set_step_output("nope", Some("hi".into())).unwrap_err();
        assert!(err.contains("unknown step id"), "got: {err}");
    }

    #[test]
    fn submit_replaces_prior_plan() {
        let _g = test_lock();
        fresh_submit(3);
        update_step("s0", StepStatus::InProgress, None).unwrap();
        update_step("s0", StepStatus::Done, None).unwrap();

        // New plan; old state is gone.
        let new_plan = submit(vec![step("alpha", "first")]).unwrap();
        assert_eq!(new_plan.steps.len(), 1);
        let active = get().unwrap();
        assert_eq!(active.id, new_plan.id);
        assert_eq!(active.steps[0].id, "alpha");
        assert!(active.step_by_id("s0").is_none());
    }
}
