//! `PptxEdit` — in-place edit of a PowerPoint deck. Single op for v1:
//! `find_replace` across all `<a:t>` text content in every
//! `ppt/slides/slide{N}.xml` part. Useful for template-fill workflows
//! ("replace `{{client}}` with the customer name across the deck").
//!
//! Like DocxEdit, the match is per-text-run — DrawingML splits text
//! across runs when style changes, so a substring spanning a styled
//! boundary won't match. For decks generated by PptxCreate this is a
//! non-issue (each bullet is a single run); for human-authored decks
//! with rich styling, the user may need to flatten styling first.

use super::{req_str, Tool};
use crate::error::{Error, Result};
use async_trait::async_trait;
use quick_xml::events::{BytesText, Event};
use quick_xml::reader::Reader;
use quick_xml::writer::Writer;
use serde_json::{json, Value};
use std::io::{Cursor, Read, Write};
use zip::write::SimpleFileOptions;
use zip::{ZipArchive, ZipWriter};

pub struct PptxEditTool;

#[async_trait]
impl Tool for PptxEditTool {
    fn name(&self) -> &'static str {
        "PptxEdit"
    }

    fn description(&self) -> &'static str {
        "Edit a PowerPoint deck (.pptx) in place. Single op for v1: \
         `find_replace` (per-run substring replace across all slides). \
         Designed for template-fill workflows: load a template with \
         `{{placeholder}}` markers, replace each marker with the real \
         value. Other OOXML parts (theme, layouts, masters) untouched."
    }

    fn input_schema(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "path":    {"type": "string", "description": "Path to the .pptx to edit (overwritten in place)."},
                "op":      {"type": "string", "enum": ["find_replace"]},
                "find":    {"type": "string", "description": "Substring to match."},
                "replace": {"type": "string", "description": "Replacement string."}
            },
            "required": ["path", "op", "find", "replace"]
        })
    }

    fn requires_approval(&self, _input: &Value) -> bool {
        true
    }

    async fn call(&self, input: Value) -> Result<String> {
        let raw_path = req_str(&input, "path")?;
        let validated = crate::sandbox::Sandbox::check_write(raw_path)?;
        let op = req_str(&input, "op")?;
        if op != "find_replace" {
            return Err(Error::Tool(format!(
                "unknown op {op:?}; expected find_replace"
            )));
        }
        let find = req_str(&input, "find")?.to_string();
        let replace = req_str(&input, "replace")?.to_string();
        if find.is_empty() {
            return Err(Error::Tool("find string must not be empty".into()));
        }

        let path_clone = validated.clone();
        tokio::task::spawn_blocking(move || apply_find_replace(&path_clone, &find, &replace))
            .await
            .map_err(|e| Error::Tool(format!("PPTX edit worker: {e}")))?
    }
}

fn apply_find_replace(path: &std::path::Path, find: &str, replace: &str) -> Result<String> {
    let bytes =
        std::fs::read(path).map_err(|e| Error::Tool(format!("read {}: {}", path.display(), e)))?;
    let mut zip =
        ZipArchive::new(Cursor::new(bytes)).map_err(|e| Error::Tool(format!("open zip: {e}")))?;

    let mut writer = ZipWriter::new(Cursor::new(Vec::<u8>::new()));
    let opts = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    let mut total_replacements = 0usize;
    let mut slides_touched = 0usize;

    for i in 0..zip.len() {
        let mut entry = zip
            .by_index(i)
            .map_err(|e| Error::Tool(format!("read entry {i}: {e}")))?;
        let name = entry.name().to_string();

        writer
            .start_file(&name, opts)
            .map_err(|e| Error::Tool(format!("zip start_file {name}: {e}")))?;

        let is_slide = name.starts_with("ppt/slides/slide") && name.ends_with(".xml");

        if is_slide {
            let mut xml = String::new();
            entry
                .read_to_string(&mut xml)
                .map_err(|e| Error::Tool(format!("decode {name}: {e}")))?;
            let (new_xml, n) = replace_in_text_runs(&xml, find, replace)?;
            if n > 0 {
                slides_touched += 1;
            }
            total_replacements += n;
            writer
                .write_all(new_xml.as_bytes())
                .map_err(|e| Error::Tool(format!("zip write {name}: {e}")))?;
        } else {
            let mut buf = Vec::with_capacity(entry.size() as usize);
            entry
                .read_to_end(&mut buf)
                .map_err(|e| Error::Tool(format!("read entry body {name}: {e}")))?;
            writer
                .write_all(&buf)
                .map_err(|e| Error::Tool(format!("zip write {name}: {e}")))?;
        }
    }

    let final_buf = writer
        .finish()
        .map_err(|e| Error::Tool(format!("zip finalize: {e}")))?
        .into_inner();

    std::fs::write(path, final_buf)
        .map_err(|e| Error::Tool(format!("write {}: {}", path.display(), e)))?;

    Ok(format!(
        "Replaced {total_replacements} occurrence(s) of {find:?} across {slides_touched} slide(s) in {}",
        path.display()
    ))
}

/// Walk one slide's XML and replace inside `<a:t>` text content only.
/// Returns the rewritten XML and the count of replacements made.
fn replace_in_text_runs(xml: &str, find: &str, replace: &str) -> Result<(String, usize)> {
    let mut reader = Reader::from_str(xml);
    reader.config_mut().trim_text(false);

    let mut out_buf: Vec<u8> = Vec::with_capacity(xml.len());
    let mut writer = Writer::new(&mut out_buf);
    let mut buf = Vec::new();
    let mut in_text = false;
    let mut count = 0usize;

    loop {
        match reader
            .read_event_into(&mut buf)
            .map_err(|e| Error::Tool(format!("xml parse: {e}")))?
        {
            Event::Start(e) => {
                if e.local_name().as_ref() == b"t" {
                    in_text = true;
                }
                writer
                    .write_event(Event::Start(e.into_owned()))
                    .map_err(|e| Error::Tool(format!("xml write: {e}")))?;
            }
            Event::End(e) => {
                if e.local_name().as_ref() == b"t" {
                    in_text = false;
                }
                writer
                    .write_event(Event::End(e.into_owned()))
                    .map_err(|e| Error::Tool(format!("xml write: {e}")))?;
            }
            Event::Text(t) => {
                if in_text {
                    let raw = t
                        .decode()
                        .map_err(|e| Error::Tool(format!("text decode: {e}")))?;
                    let unescaped = quick_xml::escape::unescape(&raw)
                        .map_err(|e| Error::Tool(format!("text unescape: {e}")))?;
                    let occurrences = unescaped.matches(find).count();
                    if occurrences > 0 {
                        let replaced = unescaped.replace(find, replace);
                        count += occurrences;
                        writer
                            .write_event(Event::Text(BytesText::new(&replaced)))
                            .map_err(|e| Error::Tool(format!("xml write: {e}")))?;
                    } else {
                        writer
                            .write_event(Event::Text(t.into_owned()))
                            .map_err(|e| Error::Tool(format!("xml write: {e}")))?;
                    }
                } else {
                    writer
                        .write_event(Event::Text(t.into_owned()))
                        .map_err(|e| Error::Tool(format!("xml write: {e}")))?;
                }
            }
            Event::Eof => break,
            other => writer
                .write_event(other.into_owned())
                .map_err(|e| Error::Tool(format!("xml write: {e}")))?,
        }
        buf.clear();
    }

    let s = String::from_utf8(out_buf).map_err(|e| Error::Tool(format!("utf-8: {e}")))?;
    Ok((s, count))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use tempfile::tempdir;

    #[tokio::test]
    async fn round_trip_create_edit_read() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("rt.pptx");

        crate::tools::PptxCreateTool
            .call(json!({
                "path": path.to_string_lossy(),
                "content": "# {{client}} Sales Pitch\n\n- {{product}} highlights\n- รายการที่ {{rank}}\n\n# {{client}} Roadmap\n\n- Phase one"
            }))
            .await
            .unwrap();

        // Replace {{client}} → "Acme" — appears in two slide titles.
        let r1 = PptxEditTool
            .call(json!({
                "path": path.to_string_lossy(),
                "op": "find_replace",
                "find": "{{client}}",
                "replace": "Acme"
            }))
            .await
            .unwrap();
        assert!(r1.contains("2 occurrence"), "expected 2 hits, got: {r1:?}");

        // Replace product placeholder.
        PptxEditTool
            .call(json!({
                "path": path.to_string_lossy(),
                "op": "find_replace",
                "find": "{{product}}",
                "replace": "ผลิตภัณฑ์"
            }))
            .await
            .unwrap();

        // Read back; verify replacements + Thai content survives.
        let extracted = crate::tools::PptxReadTool
            .call(json!({"path": path.to_string_lossy()}))
            .await
            .unwrap();
        assert!(
            extracted.contains("Acme"),
            "Acme replacement: {extracted:?}"
        );
        assert!(
            !extracted.contains("{{client}}"),
            "leftover placeholder: {extracted:?}"
        );
        assert!(
            extracted.contains("ผลิตภัณฑ์"),
            "Thai replacement: {extracted:?}"
        );
        assert!(
            extracted.contains("รายการที่"),
            "original Thai lost: {extracted:?}"
        );
    }

    #[tokio::test]
    async fn errors_on_empty_find() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("x.pptx");
        crate::tools::PptxCreateTool
            .call(json!({
                "path": path.to_string_lossy(),
                "content": "# Title"
            }))
            .await
            .unwrap();
        let err = PptxEditTool
            .call(json!({
                "path": path.to_string_lossy(),
                "op": "find_replace",
                "find": "",
                "replace": "x"
            }))
            .await
            .unwrap_err();
        assert!(format!("{err}").contains("must not be empty"));
    }
}
